/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pj_arbre;

/**
 *
 * @author axel
 */
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.LinkedHashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

public class V_Arbre extends javax.swing.JFrame {

    /**
     * Creates new form V_Inscription
     */
    private C_Arbre leControl;
    private M_Arbre unArbre;
    private LinkedHashMap<Integer, M_Individu> lesIndividus;

    public V_Arbre(java.awt.Frame parent, boolean modal, C_Arbre leControl) {
        this.leControl = leControl;
        initComponents();
    }
    
    public void afficher(M_Arbre unArbre, LinkedHashMap<Integer, M_Individu> lesIndividus){
        this.unArbre = unArbre;
        this.lesIndividus = lesIndividus;
        
        this.lb_arbre.setText(unArbre.getNom());
        this.setTitle("Arbre : " + unArbre.getNom());
        
        for (M_Individu unIndividu : lesIndividus.values()) {
            cb_individus.addItem(unIndividu.getNom() + " " + unIndividu.getPrenom());
        }
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_arbre = new javax.swing.JLabel();
        pn_arbre = new javax.swing.JPanel();
        lb_individu = new javax.swing.JLabel();
        cb_individus = new javax.swing.JComboBox<>();
        bt_individus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nom arbre");

        lb_arbre.setText("Nom Arbre");

        javax.swing.GroupLayout pn_arbreLayout = new javax.swing.GroupLayout(pn_arbre);
        pn_arbre.setLayout(pn_arbreLayout);
        pn_arbreLayout.setHorizontalGroup(
            pn_arbreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        pn_arbreLayout.setVerticalGroup(
            pn_arbreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        lb_individu.setText("Voir individu :");

        cb_individus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_individusActionPerformed(evt);
            }
        });

        bt_individus.setText("Gestion des individus");
        bt_individus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_individusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(lb_arbre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(pn_arbre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_individu)
                            .addComponent(cb_individus, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_individus))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_arbre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_arbre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_individu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_individus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_individus)))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_individusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_individusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_individusActionPerformed

    private void bt_individusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_individusActionPerformed
        try {
            leControl.aff_V_Individus(unArbre);
        } catch (SQLException ex) {
            Logger.getLogger(V_Arbre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_individusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            V_Arbre dialog = new V_Arbre(new javax.swing.JFrame(), true, null);  // Même contrôleur null ici
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_individus;
    private javax.swing.JComboBox<String> cb_individus;
    private javax.swing.JLabel lb_arbre;
    private javax.swing.JLabel lb_individu;
    private javax.swing.JPanel pn_arbre;
    // End of variables declaration//GEN-END:variables
}
