/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pj_arbre;

import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author axel
 */
public class V_Creer_Arbre extends javax.swing.JDialog {

    private C_Arbre leControl;
    private M_Utilisateur utilConnecte;
    /**
     * Creates new form V_Creer_Arbre
     */
    public V_Creer_Arbre(java.awt.Frame parent, boolean modal, C_Arbre leControl) {
        super(parent, modal);
        this.leControl = leControl;
        initComponents();
    }

    public void afficher(M_Utilisateur utilConnecte){
        this.utilConnecte = utilConnecte;
        
        lb_erreur.setVisible(false);
        
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_erreur = new javax.swing.JLabel();
        lb_nom = new javax.swing.JLabel();
        ed_nom = new javax.swing.JTextField();
        bt_enregistrer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Créer un nouvel arbre");

        lb_erreur.setForeground(new java.awt.Color(255, 0, 0));
        lb_erreur.setText("Les champs ne sont pas remplis.");

        lb_nom.setText("Nom de l'arbre :");

        bt_enregistrer.setText("Enregistrer");
        bt_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(ed_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(bt_enregistrer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lb_erreur))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lb_nom)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(lb_erreur)
                .addGap(18, 18, 18)
                .addComponent(lb_nom)
                .addGap(18, 18, 18)
                .addComponent(ed_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_enregistrer)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enregistrerActionPerformed
        String nomArbre = ed_nom.getText().trim();

        lb_erreur.setVisible(false);

        if (nomArbre.isEmpty()) {
            lb_erreur.setText("Veuillez choisir un nom pour l'arbre.");
            lb_erreur.setVisible(true);
            return;
        }

        try {
            leControl.insertArbre(nomArbre, utilConnecte.getId()); // Méthode hypothétique à adapter selon ton contrôleur
            JOptionPane.showMessageDialog(this, "L'arbre a bien été créé.", "Succès", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); // Ferme la fenêtre
        } catch (SQLException ex) {
            lb_erreur.setText("Erreur lors de la création de l'arbre.");
            lb_erreur.setVisible(true);
            Logger.getLogger(V_Creer_Arbre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_enregistrerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(V_Creer_Arbre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(V_Creer_Arbre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(V_Creer_Arbre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(V_Creer_Arbre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            V_Creer_Arbre dialog = new V_Creer_Arbre(new javax.swing.JFrame(), true, null);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_enregistrer;
    private javax.swing.JTextField ed_nom;
    private javax.swing.JLabel lb_erreur;
    private javax.swing.JLabel lb_nom;
    // End of variables declaration//GEN-END:variables
}
