/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pj_arbre;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author dirila
 */
public class V_Main extends javax.swing.JFrame {

    private M_Utilisateur unUtilisateurConnecte;
    private C_Arbre leControl;
    private Map<String, Object> menuMap = new HashMap<>();
    private JMenu mn;
    private JMenuItem mi;

    private void scanMenus(JMenuBar menuBar) {
        for (int i = 0; i < menuBar.getMenuCount(); i++) {
            mn = menuBar.getMenu(i);
            mn.setVisible(false);
            menuMap.put(mn.getName(), mn);
            for (int j = 0; j < mn.getItemCount(); j++) {
                mi = mn.getItem(j);
                mi.setVisible(false);
                menuMap.put(mi.getName(), mi);
            }
        }
    }

    private void aff_menus(M_Utilisateur unUtil) throws SQLException {
        LinkedHashMap<String, M_Action> lhmLesActions = leControl.actions_Util(unUtil);
        for (String strCle : lhmLesActions.keySet()) {
            M_Action uneAction = lhmLesActions.get(strCle);
            String code = uneAction.getCodeAction();
            String classe = menuMap.get(code).getClass().toString();
            
            if (classe.equals("class javax.swing.JMenu")) {
                JMenu menu = (JMenu) menuMap.get(code);
                menu.setVisible(true);
            } else if (classe.equals("class javax.swing.JMenuItem")) {
                JMenuItem menuItem = (JMenuItem) menuMap.get(code);
                menuItem.setVisible(true);
            }
        }
    }

    public void afficher() {
        pn_connect.setVisible(true);
        pn_accueil.setVisible(false);
        this.setLocationRelativeTo(null);
        scanMenus(mb_menu);
        this.setVisible(true);
    }

    public V_Main(C_Arbre leControleur) {
        leControl = leControleur;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_connect = new javax.swing.JPanel();
        lb_login = new javax.swing.JLabel();
        ed_login = new javax.swing.JTextField();
        lb_mdp = new javax.swing.JLabel();
        bt_connect = new javax.swing.JButton();
        pw_mdp = new javax.swing.JPasswordField();
        bt_inscription = new javax.swing.JButton();
        pn_accueil = new javax.swing.JPanel();
        lb_bonjour = new javax.swing.JLabel();
        mb_menu = new javax.swing.JMenuBar();
        mn_compte = new javax.swing.JMenu();
        mi_parametres = new javax.swing.JMenuItem();
        mn_arbres = new javax.swing.JMenu();
        mi_creer = new javax.swing.JMenuItem();
        mi_arbres = new javax.swing.JMenuItem();
        mn_admin = new javax.swing.JMenu();
        mi_utilisateurs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Application Arbre");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        lb_login.setText("Login :");

        ed_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ed_loginActionPerformed(evt);
            }
        });

        lb_mdp.setText("Mdp :");

        bt_connect.setText("Connexion");
        bt_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_connectActionPerformed(evt);
            }
        });

        bt_inscription.setText("Inscription");
        bt_inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inscriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_connectLayout = new javax.swing.GroupLayout(pn_connect);
        pn_connect.setLayout(pn_connectLayout);
        pn_connectLayout.setHorizontalGroup(
            pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_connectLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_connectLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_login)
                            .addComponent(lb_mdp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ed_login)
                            .addComponent(pw_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_connectLayout.createSequentialGroup()
                        .addComponent(bt_connect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_inscription)
                        .addGap(34, 34, 34)))
                .addGap(44, 44, 44))
        );
        pn_connectLayout.setVerticalGroup(
            pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_connectLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_login)
                    .addComponent(ed_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mdp)
                    .addComponent(pw_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_connect)
                    .addComponent(bt_inscription))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pn_connect, "card2");

        lb_bonjour.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lb_bonjour.setText("Bonjour");

        javax.swing.GroupLayout pn_accueilLayout = new javax.swing.GroupLayout(pn_accueil);
        pn_accueil.setLayout(pn_accueilLayout);
        pn_accueilLayout.setHorizontalGroup(
            pn_accueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_accueilLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lb_bonjour)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        pn_accueilLayout.setVerticalGroup(
            pn_accueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_accueilLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(lb_bonjour)
                .addGap(75, 75, 75))
        );

        getContentPane().add(pn_accueil, "card4");

        mn_compte.setText("Compte");
        mn_compte.setName("mn_compte"); // NOI18N

        mi_parametres.setText("Paramètres");
        mi_parametres.setName("mi_parametres"); // NOI18N
        mi_parametres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_parametresActionPerformed(evt);
            }
        });
        mn_compte.add(mi_parametres);

        mb_menu.add(mn_compte);

        mn_arbres.setText("Arbres");
        mn_arbres.setName("mn_arbres"); // NOI18N

        mi_creer.setText("Créer un arbre");
        mi_creer.setName("mi_creer"); // NOI18N
        mi_creer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_creerActionPerformed(evt);
            }
        });
        mn_arbres.add(mi_creer);

        mi_arbres.setText("Liste des arbres");
        mi_arbres.setName("mi_arbres"); // NOI18N
        mi_arbres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_arbresActionPerformed(evt);
            }
        });
        mn_arbres.add(mi_arbres);

        mb_menu.add(mn_arbres);

        mn_admin.setText("Administation");
        mn_admin.setName("mn_admin"); // NOI18N

        mi_utilisateurs.setText("Liste des utilisateurs");
        mi_utilisateurs.setName("mi_utilisateurs"); // NOI18N
        mi_utilisateurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_utilisateursActionPerformed(evt);
            }
        });
        mn_admin.add(mi_utilisateurs);

        mb_menu.add(mn_admin);

        setJMenuBar(mb_menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_connectActionPerformed

        String strLogin = ed_login.getText();
        String strMdp = pw_mdp.getText();
        try {
            unUtilisateurConnecte = leControl.verif_utilisateur(strLogin, strMdp);
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (unUtilisateurConnecte == null) {
            afficher();
            JOptionPane.showMessageDialog(this, "Identifiant ou mot de passe "
                    + "incorrect. Veuillez réessayer.","Erreur",JOptionPane.ERROR_MESSAGE);
            ed_login.setText("");
            pw_mdp.setText("");
        } else {
            pn_connect.setVisible(false);
            pn_accueil.setVisible(true);
            lb_bonjour.setText("Bonjour, " + unUtilisateurConnecte.getLogin() + ".");
            try {
                aff_menus(unUtilisateurConnecte);
            } catch (SQLException ex) {
                Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_bt_connectActionPerformed

    private void mi_creerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_creerActionPerformed
        leControl.aff_V_Creer_Arbre();
    }//GEN-LAST:event_mi_creerActionPerformed

    private void mi_parametresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_parametresActionPerformed
        try {
            leControl.aff_V_MonCompte();
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_parametresActionPerformed

    private void bt_inscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inscriptionActionPerformed
        try {
            leControl.aff_V_Inscription();
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_inscriptionActionPerformed

    private void mi_arbresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_arbresActionPerformed
        try {
            leControl.aff_V_MesArbres();
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_arbresActionPerformed

    private void mi_utilisateursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_utilisateursActionPerformed
        try {
            leControl.aff_V_Utilisateurs();
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_utilisateursActionPerformed

    private void ed_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ed_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ed_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Main(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_connect;
    private javax.swing.JButton bt_inscription;
    private javax.swing.JTextField ed_login;
    private javax.swing.JLabel lb_bonjour;
    private javax.swing.JLabel lb_login;
    private javax.swing.JLabel lb_mdp;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenuItem mi_arbres;
    private javax.swing.JMenuItem mi_creer;
    private javax.swing.JMenuItem mi_parametres;
    private javax.swing.JMenuItem mi_utilisateurs;
    private javax.swing.JMenu mn_admin;
    private javax.swing.JMenu mn_arbres;
    private javax.swing.JMenu mn_compte;
    private javax.swing.JPanel pn_accueil;
    private javax.swing.JPanel pn_connect;
    private javax.swing.JPasswordField pw_mdp;
    // End of variables declaration//GEN-END:variables
}
