/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pj_arbre;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author dirila
 */
public class V_Main extends javax.swing.JFrame {

    private M_Utilisateur utilConnecte;
    private C_Arbre leControl;
    private Map<String, Object> menuMap = new HashMap<>();
    private JMenu mn;
    private JMenuItem mi;

    private void scanMenus(JMenuBar menuBar) {
        for (int i = 0; i < menuBar.getMenuCount(); i++) {
            mn = menuBar.getMenu(i);
            mn.setVisible(false);
            menuMap.put(mn.getName(), mn);
            for (int j = 0; j < mn.getItemCount(); j++) {
                mi = mn.getItem(j);
                mi.setVisible(false);
                menuMap.put(mi.getName(), mi);
            }
        }
    }

    private void aff_menus(M_Utilisateur unUtil) throws SQLException {
        LinkedHashMap<String, M_Action> lesActions = leControl.actions_Util(unUtil);
        for (String cle : lesActions.keySet()) {
            M_Action uneAction = lesActions.get(cle);
            String code = uneAction.getCodeAction();
            String classe = menuMap.get(code).getClass().toString();
            if (classe.equals("class javax.swing.JMenu")) {
                JMenu menu = (JMenu) menuMap.get(code);
                menu.setVisible(true);
            } else if (classe.equals("class javax.swing.JMenuItem")) {
                JMenuItem menuItem = (JMenuItem) menuMap.get(code);
                menuItem.setVisible(true);
            }
        }
    }

    public void afficher() {
        lb_message.setVisible(false);
        pn_connect.setVisible(true);
        this.setTitle("Application Arbre");
        this.setLocationRelativeTo(null);
        scanMenus(mb_menu);
        this.setVisible(true);
    }

    public V_Main(C_Arbre leControleur) {
        leControl = leControleur;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_connect = new javax.swing.JPanel();
        lb_login = new javax.swing.JLabel();
        ed_login = new javax.swing.JTextField();
        lb_mdp = new javax.swing.JLabel();
        bt_connect = new javax.swing.JButton();
        lb_message = new javax.swing.JLabel();
        pw_mdp = new javax.swing.JPasswordField();
        bt_inscription = new javax.swing.JButton();
        mb_menu = new javax.swing.JMenuBar();
        mn_compte = new javax.swing.JMenu();
        mi_parametres = new javax.swing.JMenuItem();
        mn_arbres = new javax.swing.JMenu();
        mi_creer = new javax.swing.JMenuItem();
        mi_arbres = new javax.swing.JMenuItem();
        mn_admin = new javax.swing.JMenu();
        mi_utilisateurs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil");

        lb_login.setText("Login :");

        lb_mdp.setText("Mdp :");

        bt_connect.setText("Connexion");
        bt_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_connectActionPerformed(evt);
            }
        });

        lb_message.setForeground(new java.awt.Color(204, 0, 0));
        lb_message.setText("Erreur de connexion");

        bt_inscription.setText("Inscription");
        bt_inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inscriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_connectLayout = new javax.swing.GroupLayout(pn_connect);
        pn_connect.setLayout(pn_connectLayout);
        pn_connectLayout.setHorizontalGroup(
            pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_connectLayout.createSequentialGroup()
                .addGroup(pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_connectLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lb_message))
                    .addGroup(pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_connectLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(bt_connect)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                            .addComponent(bt_inscription))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_connectLayout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lb_login)
                                .addComponent(lb_mdp))
                            .addGap(32, 32, 32)
                            .addGroup(pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ed_login, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addComponent(pw_mdp)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pn_connectLayout.setVerticalGroup(
            pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_connectLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(lb_message)
                .addGap(18, 18, 18)
                .addGroup(pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_login)
                    .addComponent(ed_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mdp)
                    .addComponent(pw_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pn_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_connect)
                    .addComponent(bt_inscription))
                .addGap(32, 32, 32))
        );

        mn_compte.setText("Compte");
        mn_compte.setName("mn_compte"); // NOI18N

        mi_parametres.setText("Paramètres");
        mi_parametres.setName("mi_parametres"); // NOI18N
        mi_parametres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_parametresActionPerformed(evt);
            }
        });
        mn_compte.add(mi_parametres);

        mb_menu.add(mn_compte);

        mn_arbres.setText("Arbres");
        mn_arbres.setName("mn_arbres"); // NOI18N

        mi_creer.setText("Créer un arbre");
        mi_creer.setName("mi_creer"); // NOI18N
        mi_creer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_creerActionPerformed(evt);
            }
        });
        mn_arbres.add(mi_creer);

        mi_arbres.setText("Liste des arbres");
        mi_arbres.setName("mi_arbres"); // NOI18N
        mi_arbres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_arbresActionPerformed(evt);
            }
        });
        mn_arbres.add(mi_arbres);

        mb_menu.add(mn_arbres);

        mn_admin.setText("Administation");
        mn_admin.setName("mn_admin"); // NOI18N

        mi_utilisateurs.setText("Liste des utilisateurs");
        mi_utilisateurs.setName("mi_utilisateurs"); // NOI18N
        mn_admin.add(mi_utilisateurs);

        mb_menu.add(mn_admin);

        setJMenuBar(mb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(pn_connect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pn_connect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_connectActionPerformed

        String login = ed_login.getText();
        String mdp = pw_mdp.getText();
        try {
            utilConnecte = leControl.verif_utilisateur(login, mdp);
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (utilConnecte == null) {
            afficher();
            lb_message.setVisible(true);
        } else {
            pn_connect.setVisible(false);
            try {
                aff_menus(utilConnecte);
            } catch (SQLException ex) {
                Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_bt_connectActionPerformed

    private void mi_creerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_creerActionPerformed
        leControl.aff_V_Creer_Arbre();
    }//GEN-LAST:event_mi_creerActionPerformed

    private void mi_parametresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_parametresActionPerformed
        try {
            leControl.aff_V_MonCompte();
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_parametresActionPerformed

    private void bt_inscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inscriptionActionPerformed
        try {
            leControl.aff_V_Inscription();
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_inscriptionActionPerformed

    private void mi_arbresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_arbresActionPerformed
        try {
            leControl.aff_V_MesArbres();
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_arbresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Main(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_connect;
    private javax.swing.JButton bt_inscription;
    private javax.swing.JTextField ed_login;
    private javax.swing.JLabel lb_login;
    private javax.swing.JLabel lb_mdp;
    private javax.swing.JLabel lb_message;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenuItem mi_arbres;
    private javax.swing.JMenuItem mi_creer;
    private javax.swing.JMenuItem mi_parametres;
    private javax.swing.JMenuItem mi_utilisateurs;
    private javax.swing.JMenu mn_admin;
    private javax.swing.JMenu mn_arbres;
    private javax.swing.JMenu mn_compte;
    private javax.swing.JPanel pn_connect;
    private javax.swing.JPasswordField pw_mdp;
    // End of variables declaration//GEN-END:variables
}
