/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pj_arbre;

import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dirila
 */
public class V_MonCompte extends javax.swing.JDialog {

    private C_Arbre leControl;
    private M_Utilisateur unUtilisateur;
    
    public V_MonCompte(java.awt.Frame parent, boolean modal, C_Arbre leControl) {
        super(parent, modal);
        this.leControl = leControl;
        initComponents();
    }

    public void afficher(M_Utilisateur unUtilisateur){
        this.unUtilisateur = unUtilisateur;
        ed_login.setText(unUtilisateur.getLogin());
        ed_mail.setText(unUtilisateur.getMail());
        
        ed_login.setEditable(false);
        ed_mail.setEditable(false);
        
        bt_modifier.setVisible(true);
        bt_modifier_mdp.setVisible(true);
        bt_enregistrer.setVisible(false);
        bt_annuler.setVisible(false);
        
        pn_Utilisateur.setVisible(true);
        pn_MP.setVisible(false);

        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public void vider(){
        pw_mp_ancien.setText("");
        pw_mp_nouv.setText("");
        pw_mp_conf.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_MP = new javax.swing.JPanel();
        lb_mp_actuel = new javax.swing.JLabel();
        lb_nouv_mp = new javax.swing.JLabel();
        lb_conf_mp = new javax.swing.JLabel();
        pw_mp_ancien = new javax.swing.JPasswordField();
        pw_mp_nouv = new javax.swing.JPasswordField();
        pw_mp_conf = new javax.swing.JPasswordField();
        bt_annuler_mdp = new javax.swing.JButton();
        bt_enregistrer_mdp = new javax.swing.JButton();
        pn_Utilisateur = new javax.swing.JPanel();
        lb_login = new javax.swing.JLabel();
        ed_login = new javax.swing.JTextField();
        bt_modifier = new javax.swing.JButton();
        bt_modifier_mdp = new javax.swing.JButton();
        bt_enregistrer = new javax.swing.JButton();
        bt_annuler = new javax.swing.JButton();
        lb_mail = new javax.swing.JLabel();
        ed_mail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mon compte");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        lb_mp_actuel.setText("Mot de passe actuel :");

        lb_nouv_mp.setText("Nouveau mot de passe :");

        lb_conf_mp.setText("Confirmer nouveau mot de passe :");

        pw_mp_nouv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw_mp_nouvActionPerformed(evt);
            }
        });

        bt_annuler_mdp.setText("Annuler");
        bt_annuler_mdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_annuler_mdpActionPerformed(evt);
            }
        });

        bt_enregistrer_mdp.setText("Enregistrer");
        bt_enregistrer_mdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enregistrer_mdpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_MPLayout = new javax.swing.GroupLayout(pn_MP);
        pn_MP.setLayout(pn_MPLayout);
        pn_MPLayout.setHorizontalGroup(
            pn_MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_MPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pw_mp_conf)
                    .addComponent(pw_mp_nouv)
                    .addComponent(pw_mp_ancien)
                    .addGroup(pn_MPLayout.createSequentialGroup()
                        .addGroup(pn_MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_nouv_mp)
                            .addComponent(lb_conf_mp)
                            .addComponent(lb_mp_actuel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pn_MPLayout.createSequentialGroup()
                        .addComponent(bt_enregistrer_mdp, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_annuler_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pn_MPLayout.setVerticalGroup(
            pn_MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_MPLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lb_mp_actuel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pw_mp_ancien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_nouv_mp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pw_mp_nouv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_conf_mp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pw_mp_conf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(pn_MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_annuler_mdp)
                    .addComponent(bt_enregistrer_mdp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pn_MP, "card3");

        lb_login.setText("Login :");

        bt_modifier.setText("Modifier");
        bt_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modifierActionPerformed(evt);
            }
        });

        bt_modifier_mdp.setText("Modifier Mdp");
        bt_modifier_mdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modifier_mdpActionPerformed(evt);
            }
        });

        bt_enregistrer.setText("Enregistrer");
        bt_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enregistrerActionPerformed(evt);
            }
        });

        bt_annuler.setText("Annuler");
        bt_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_annulerActionPerformed(evt);
            }
        });

        lb_mail.setText("Mail :");

        javax.swing.GroupLayout pn_UtilisateurLayout = new javax.swing.GroupLayout(pn_Utilisateur);
        pn_Utilisateur.setLayout(pn_UtilisateurLayout);
        pn_UtilisateurLayout.setHorizontalGroup(
            pn_UtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_UtilisateurLayout.createSequentialGroup()
                .addGroup(pn_UtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_UtilisateurLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pn_UtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_login)
                            .addComponent(lb_mail))
                        .addGap(21, 21, 21)
                        .addGroup(pn_UtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ed_login)
                            .addComponent(ed_mail)))
                    .addGroup(pn_UtilisateurLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(pn_UtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_modifier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_enregistrer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_UtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_modifier_mdp))
                        .addGap(10, 10, 10)))
                .addGap(19, 19, 19))
        );
        pn_UtilisateurLayout.setVerticalGroup(
            pn_UtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_UtilisateurLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pn_UtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ed_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_UtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ed_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_mail))
                .addGap(18, 18, 18)
                .addGroup(pn_UtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_modifier_mdp)
                    .addComponent(bt_modifier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_UtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_annuler)
                    .addComponent(bt_enregistrer))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(pn_Utilisateur, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_modifier_mdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modifier_mdpActionPerformed
        pn_Utilisateur.setVisible(false);
        pn_MP.setVisible(true);
    }//GEN-LAST:event_bt_modifier_mdpActionPerformed

    private void bt_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modifierActionPerformed
        ed_login.setEditable(true);
        ed_mail.setEditable(true);
        
        bt_modifier.setVisible(false);
        bt_modifier_mdp.setVisible(false);
        
        bt_enregistrer.setVisible(true);
        bt_annuler.setVisible(true);
    }//GEN-LAST:event_bt_modifierActionPerformed

    private void bt_enregistrer_mdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enregistrer_mdpActionPerformed
        String strAncienMp = new String(pw_mp_ancien.getPassword());
        String strNouveauMp = new String(pw_mp_nouv.getPassword());
        String strConfMp = new String(pw_mp_conf.getPassword());

        if (!strAncienMp.isEmpty() && !strNouveauMp.isEmpty() && !strConfMp.isEmpty()) {
            if (strNouveauMp.equals(strConfMp)) {
                int id = unUtilisateur.getIdUtilisateur();
                String strLogin = unUtilisateur.getLogin();

                try {
                    if (leControl.verif_Mp(id, strLogin, strAncienMp, strNouveauMp)) {
                        vider();
                        JOptionPane.showMessageDialog(null,
                            "Le mot de passe a bien été mis à jour.", "Mise à jour",
                            JOptionPane.INFORMATION_MESSAGE);
                        afficher(unUtilisateur);
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "L'ancien mot de passe est incorrect.",
                                "Erreur",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(V_MonCompte.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "Les mots de passe ne correspondent pas.",
                        "Erreur",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Tous les champs ne sont pas complétés.",
                    "Erreur",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_enregistrer_mdpActionPerformed

    private void bt_annuler_mdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_annuler_mdpActionPerformed
        vider();
        afficher(unUtilisateur);
    }//GEN-LAST:event_bt_annuler_mdpActionPerformed

    private void bt_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_annulerActionPerformed
        afficher(unUtilisateur);
    }//GEN-LAST:event_bt_annulerActionPerformed

    private void bt_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enregistrerActionPerformed
        if(!ed_login.getText().isEmpty() && !ed_mail.getText().isEmpty()){
            try {
                leControl.update_Compte(unUtilisateur.getIdUtilisateur(),
                        ed_login.getText(), ed_mail.getText());
                JOptionPane.showMessageDialog(null, "Votre compte a bien été mis à jour.",
                        "Mise à jour", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(V_MonCompte.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
                JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs",
                        "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_enregistrerActionPerformed

    private void pw_mp_nouvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw_mp_nouvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pw_mp_nouvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_MonCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_MonCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_MonCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_MonCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                V_MonCompte dialog = new V_MonCompte(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_annuler;
    private javax.swing.JButton bt_annuler_mdp;
    private javax.swing.JButton bt_enregistrer;
    private javax.swing.JButton bt_enregistrer_mdp;
    private javax.swing.JButton bt_modifier;
    private javax.swing.JButton bt_modifier_mdp;
    private javax.swing.JTextField ed_login;
    private javax.swing.JTextField ed_mail;
    private javax.swing.JLabel lb_conf_mp;
    private javax.swing.JLabel lb_login;
    private javax.swing.JLabel lb_mail;
    private javax.swing.JLabel lb_mp_actuel;
    private javax.swing.JLabel lb_nouv_mp;
    private javax.swing.JPanel pn_MP;
    private javax.swing.JPanel pn_Utilisateur;
    private javax.swing.JPasswordField pw_mp_ancien;
    private javax.swing.JPasswordField pw_mp_conf;
    private javax.swing.JPasswordField pw_mp_nouv;
    // End of variables declaration//GEN-END:variables
}
