/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pj_arbre;

import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author axel
 */
public class V_Utilisateurs extends javax.swing.JFrame {

    /**
     * Creates new form V_Utilisateurs
     */
    private C_Arbre leControl;
    private LinkedHashMap <Integer, M_Utilisateur> lhmLesUtilisateurs;
    private DefaultTableModel dtm_tb_util;
    private Object[] objTableauCles;
    private int iLigne;
    private int iCle;
    private boolean bIsModif;
    private M_Utilisateur unUtilisateurConnecte;
    
    public V_Utilisateurs(java.awt.Frame parent, boolean modal, C_Arbre leControl) {
        this.leControl = leControl;
        initComponents();
    }
    
    public void afficher(LinkedHashMap <Integer, M_Utilisateur> lhmLesUtilisateurs,
            M_Utilisateur unUtilisateurConnecte){
        this.lhmLesUtilisateurs = lhmLesUtilisateurs;
        this.unUtilisateurConnecte = unUtilisateurConnecte;
        
        this.modeEdit(false);
        
        aff_cms();
        
        dtm_tb_util = new DefaultTableModel();
        dtm_tb_util = (DefaultTableModel) tb_util.getModel();
        dtm_tb_util.setRowCount(lhmLesUtilisateurs.size());
        
        // Remplir les utilisateurs
        
        iLigne = 0;
        
        for(Integer uneCle : lhmLesUtilisateurs.keySet()){
            M_Utilisateur unUtilisateur = lhmLesUtilisateurs.get(uneCle);
            
            dtm_tb_util.setValueAt(unUtilisateur.getIdUtilisateur(), iLigne, 0);
            dtm_tb_util.setValueAt(unUtilisateur.getLogin(), iLigne, 1);
            
            iLigne++;
        }
        
        iLigne = 0;
        
        // Séléction par défaut et remplissage automatique
        
        tb_util.setRowSelectionInterval(0, 0);
        remplirChamps();
        
        this.setLocationRelativeTo(null);
        this.setSize(500, 520);
        this.setVisible(true);
    }
    
    public void aff_am(){
        this.modeEdit(true);
        
        // Afficher les bons panels
        
        pn_am.setVisible(true);
        pn_cms.setVisible(false);
        
        //Afficher les bons champs
        
        ed_maj.setVisible(true);
        lb_maj.setVisible(true);
    }
    
    public void aff_cms(){
        // Afficher les bons panels
        
        pn_am.setVisible(false);
        pn_cms.setVisible(true);
    }
    
    public void remplirChamps(){
        // Récupérer la clé
        
        
        iLigne = tb_util.getSelectedRow();
        iCle = (int) dtm_tb_util.getValueAt(iLigne, 0);
        
        // Remplir les champs
        
        M_Utilisateur unUtil = lhmLesUtilisateurs.get(iCle);
        
        ed_id.setText(String.valueOf(unUtil.getIdUtilisateur()));
        ed_mail.setText(unUtil.getMail());
        
        LocalDateTime dateDM = unUtil.getDateCreation();
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("dd//MM/yyyy HH:mm");
        String strDateEnChaine = dateDM.format(dateFormat);

        ed_maj.setText(strDateEnChaine);
        ed_login.setText(unUtil.getLogin());
        
    }
    
    public void modeEdit(Boolean active){
        ed_mail.setEditable(active);
        ed_login.setEditable(active);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sc_util = new javax.swing.JScrollPane();
        tb_util = new javax.swing.JTable();
        lb_id = new javax.swing.JLabel();
        lb_mail = new javax.swing.JLabel();
        lb_login = new javax.swing.JLabel();
        lb_maj = new javax.swing.JLabel();
        ed_id = new javax.swing.JTextField();
        ed_mail = new javax.swing.JTextField();
        ed_login = new javax.swing.JTextField();
        ed_maj = new javax.swing.JTextField();
        pn_am = new javax.swing.JPanel();
        bt_enregistrer = new javax.swing.JButton();
        bt_annuler = new javax.swing.JButton();
        pn_cms = new javax.swing.JPanel();
        bt_supprimer = new javax.swing.JButton();
        bt_modifier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion des utilisateurs");
        setResizable(false);

        tb_util.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Login"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_util.getTableHeader().setReorderingAllowed(false);
        tb_util.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_utilMouseClicked(evt);
            }
        });
        sc_util.setViewportView(tb_util);

        lb_id.setText("ID :");

        lb_mail.setText("Mail :");

        lb_login.setText("Login :");

        lb_maj.setText("Création");

        ed_id.setEditable(false);

        ed_mail.setEditable(false);

        ed_login.setEditable(false);

        ed_maj.setEditable(false);

        bt_enregistrer.setText("Enregistrer");
        bt_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enregistrerActionPerformed(evt);
            }
        });

        bt_annuler.setText("Annuler");
        bt_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_amLayout = new javax.swing.GroupLayout(pn_am);
        pn_am.setLayout(pn_amLayout);
        pn_amLayout.setHorizontalGroup(
            pn_amLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_amLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_amLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bt_annuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_enregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_amLayout.setVerticalGroup(
            pn_amLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_amLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_enregistrer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_annuler)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_supprimer.setText("Supprimer");
        bt_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_supprimerActionPerformed(evt);
            }
        });

        bt_modifier.setText("Modifier");
        bt_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_cmsLayout = new javax.swing.GroupLayout(pn_cms);
        pn_cms.setLayout(pn_cmsLayout);
        pn_cmsLayout.setHorizontalGroup(
            pn_cmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cmsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pn_cmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_modifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_cmsLayout.setVerticalGroup(
            pn_cmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_cmsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_modifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_supprimer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sc_util, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_maj)
                            .addComponent(lb_login, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ed_id, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ed_mail)
                            .addComponent(ed_login)
                            .addComponent(ed_maj))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(pn_am, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn_cms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sc_util, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(pn_cms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lb_id))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(ed_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ed_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_mail))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_login)
                            .addComponent(ed_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ed_maj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_maj, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pn_am, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_utilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_utilMouseClicked
        if(pn_cms.isVisible() && (tb_util.getSelectedRow()!=-1)){
            remplirChamps();
        }
    }//GEN-LAST:event_tb_utilMouseClicked

    private void bt_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enregistrerActionPerformed

        // Valoriser les paramètres

        String strMail = ed_mail.getText();
        String strLogin = ed_login.getText();

        // Vérifier si tous les champs sont remplis

        if(!strMail.isEmpty() && !strLogin.isEmpty()){
            // Vérifie si on est en modification
            
            if(bIsModif == true){
                try {
                    leControl.update_Compte(iCle, strLogin, strMail);
                    JOptionPane.showMessageDialog(null, "Le compte a bien été mis à jour.",
                            "Mise à jour", JOptionPane.INFORMATION_MESSAGE);
                    leControl.aff_V_Utilisateurs();
                } catch (SQLException ex) {
                    Logger.getLogger(V_Utilisateurs.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_bt_enregistrerActionPerformed

    private void bt_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_annulerActionPerformed
        aff_cms();
        modeEdit(false);
        remplirChamps();
    }//GEN-LAST:event_bt_annulerActionPerformed

    private void bt_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_supprimerActionPerformed
        if(iCle == unUtilisateurConnecte.getIdUtilisateur()){
            JOptionPane.showMessageDialog(this, "Vous ne pouvez pas supprimer votre propre compte.",
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        }
        else{
            int reponse = JOptionPane.showConfirmDialog(this,
                    "Etes-vous sûr de vouloir de supprimer cet utilisateur ?", "Suppression",
                    JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if(reponse == JOptionPane.YES_OPTION){
                try {
                    leControl.delete_Compte(iCle);
                    JOptionPane.showMessageDialog(null, "Le compte a bien été supprimé.",
                            "Mise à jour", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(V_Utilisateurs.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_bt_supprimerActionPerformed

    private void bt_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modifierActionPerformed
        aff_am();

        bIsModif = true;

        modeEdit(true);

        //Afficher les bons champs
        
        ed_maj.setVisible(true);
        lb_maj.setVisible(true);
    }//GEN-LAST:event_bt_modifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                V_Utilisateurs dialog = new V_Utilisateurs(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_annuler;
    private javax.swing.JButton bt_enregistrer;
    private javax.swing.JButton bt_modifier;
    private javax.swing.JButton bt_supprimer;
    private javax.swing.JTextField ed_id;
    private javax.swing.JTextField ed_login;
    private javax.swing.JTextField ed_mail;
    private javax.swing.JTextField ed_maj;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_login;
    private javax.swing.JLabel lb_mail;
    private javax.swing.JLabel lb_maj;
    private javax.swing.JPanel pn_am;
    private javax.swing.JPanel pn_cms;
    private javax.swing.JScrollPane sc_util;
    private javax.swing.JTable tb_util;
    // End of variables declaration//GEN-END:variables
}
